<?xml version="1.0"?>
<package format="3">
  <name>drone</name>
  <version>0.1.0</version>
  <description>Minimal ROS 2 drone workspace.</description>
  <maintainer email="cenkerusta@outlook.com">Cenker Usta</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
